### ISSUE TITLE
Backup directories shows as 0 MB

### ISSUE THREAD

**Issue by smenzer** [droboports/crashplan#18]
I'm not sure if this is a problem with the crashplan droboport or something else, so thought I'd start here in case you can help.  

I was able to use the CrashPlan UI to access my drobo and setup files to backup.  However, after initially scanning the directories and starting a backup, now it is showing each directory as 0MB even though there are gigabytes of data inside:
![image](https://cloud.githubusercontent.com/assets/624392/11008211/0b875e10-849d-11e5-9f02-f2cfbe30bc6a.png)

```
# pwd
/mnt/DroboFS/Shares

# du -hd1 .
720.4G	./DroboApps
48.0G	./Backup
66.9G	./Photos
67.4G	./Music
902.7G	.

# ls -la
drwxrwxrwx    6 Admin    Admin        4096 Oct 17 16:35 .
drwxrwxrwx    6 Admin    Admin        4096 Nov  6 12:44 ..
drwxrwxrwx   14 Admin    Admin        4096 Nov  5 08:36 Backup
drwxrwxrwx   11 Admin    Admin        4096 Nov  6 13:03 DroboApps
drwxrwxrwx  509 Admin    Admin       20480 Oct 31 13:39 Music
drwxrwxrwx   49 Admin    Admin        4096 Oct 29 13:51 Photos
```

I've tried forcing a rescan (using the crashplan UI to enter the `scan` command in the command prompt) but it didn't change anything.  Any thoughts on what's going on or what I can do to correct it?

**Comment by ricardopadilha** [comment]
Which Drobo do you have (FS or 5N)? Which firmware are you running? Which version of Drobo Dashboard?

Did you start Crashplan as root? I see that all files are owned by Admin. Maybe it is a permission problem.

**Comment by smenzer** [comment]
Hi @ricardopadilha - I have the Drobo FS running `1.2.7 [4.45.10288]` and Dashboard version `2.7.0 [77097]`

When you say "start Crashplan as root", do you mean when I log into the Drobo via command line?  If so, then yes, I ssh to the drobo using `root` username.  

Regarding permissions, since the directories and files are all permissioned to `777` shouldn't it not really matter who owns them?

Thanks!

**Comment by ricardopadilha** [comment]
Ok, can you see the configuration page at http://drobo.ip.address.here:8080/crashplan/ ?

If so, can you please post the logs somewhere? Be careful, there is some private information there.

I'm looking for error messages and java exceptions.

**Comment by smenzer** [comment]
Yep, I can get to the config page.  I copied the whole "Log Information" section into a text file and put it here: `https://www.dropbox.com/s/4krx0v93r9rka2g/DroboLogs%2011-09-15.log?dl=0` - please let me know once you have read it so I can take it down.

Thanks!
Scott

**Comment by ricardopadilha** [comment]
I had a look at the log files, and things seem to be working. Have a look at this (history.log.0):
```
I 11/05/15 12:09PM Backup scheduled to always run
I 11/05/15 12:09PM [Default] Scanning for files to back up
I 11/05/15 12:10PM Archive maintenance for Drobo XXXX.
I 11/05/15 12:37PM [Default] Scanning for files completed in 28 minutes: 99,443 files (143.60GB) found
I 11/05/15 01:46PM Archive maintenance: Complete for Drobo XXXX.
...
I 11/05/15 06:33PM Starting backup from XXXX: 1,075 files (144.40MB) to back up
I 11/05/15 06:40PM Starting backup from XXXX: 1,056 files (141.20MB) to back up
I 11/05/15 06:55PM Stopped backup from XXXX in 15 minutes: 0 files (1.30MB) backed up, 2.30MB received @ 1Mbps
I 11/05/15 06:55PM  - Reason for stopping backup: The backup destination was disconnected
```

You seem to have a filesystem error. Look at this from `backup_files.log.0`:
```
W 11/07/15 05:15AM 42  - Jericho.m4aï¿½QeMï¿½ï¿½ï¿½ï¿½ï¿½Òï¿½ï¿½3ï¿½1ï¿½ï¿½ï¿½_&ï¿½Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½E/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/15 Wishing.m4aï¿½Ð¤Mï¿½ï¿½ï¿½xvï¿½ï¿½Ó¥ï¿½ï¿½Iï¿½ï¿½	ï¿½3Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½\/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/16 Life In A Northern Town [Live].m4aï¿½Lï¿½Mï¿½ï¿½ï¿½8NkmMï¿½ï¿½ï¿½Z;ï¿½ï¿½Rï¿½ï¿½ï¿½Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½J/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/07 Already Gone.m4ax@ï¿½Mï¿½ï¿½ï¿½HÌï¿½ï¿½ï¿½ï¿½ï¿½O@ï¿½R{6Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½T/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/12 Very Last Country Song.m4aï¿½ï¿½jMï¿½ï¿½ï¿½È[{mï¿½Uï¿½ï¿½{4ï¿½k=ÞFï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½B/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/04 Joey.m4aï¿½	ï¿½Mï¿½ï¿½É¨ï¿½ï¿½ï¿½6ï¿½ï¿½ï¿½ï¿½Sï¿½U2Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½K/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/10 What I'd Give.m4aï¿½cLMï¿½ï¿½ï¿½ ï¿½ï¿½Hï¿½Vï¿½|ï¿½^5ï¿½b&Ì¤Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½F/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/08 Keep You.m4aï¿½1ï¿½Mï¿½ï¿½ï¿½!ï¿½ï¿½{"Úï¿½ï¿½|ï¿½Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½J/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/13 Fall Into Me.m4aï¿½\Mï¿½ï¿½ï¿½ï¿½oï¿½ï¿½S*ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½)Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½W/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/17 Come On Get Higher [Live].m4aï¿½<>Mï¿½ï¿½ï¿½ï¿½2Mjï¿½ï¿½ï¿½ï¿½vNï¿½(OÇ¦8ï¿½Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½M/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/09 Take Me As I Am.m4aï¿½ï¿½Mï¿½ï¿½ï¿½ï¿½ï¿½BÔï¿½5á§ï¿½ï¿½ï¿½@ï¿½Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½B/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/05 Love.m4avï¿½hMï¿½ï¿½ï¿½`ï¿½=be_/=ï¿½	ï¿½ï¿½ï¿½ï¿½Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½I/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/11 Steve Earle.m4aonWMï¿½ï¿½ï¿½Pï¿½0Ú¸ï¿½m	ï¿½vYï¿½ï¿½ï¿½4Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½G/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/06 Genevieve.m4a~=Mï¿½ï¿½ï¿½ï¿½tï¿½3&ï¿½ï¿½Rï¿½Zsï¿½jï¿½Jï¿½Fï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½D/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/03 We Run.m4avDï¿½Mï¿½ï¿½ï¿½@.ï¿½ï¿½ï¿½ï¿½?ï¿½pï¿½qï¿½PFï¿½ï¿½ï¿½Hï¿½cï¿½ï¿½/ï¿½3#ï¿½ï¿½ï¿½N/mnt/DroboFS/Shares/Music/Sugarland/Love On The Inside/01 All I Want To Do.m4aï¿½qï¿½Mï¿½ï¿½ï¿½xï¿½Hï¿½gï¿½ï¿½
```

This looks like some pretty bad filesystem corruption. Please have a look at this support article from Drobo: http://support.drobo.com/app/answers/detail/a_id/500
