### ISSUE TITLE
New version of CrashPlan 4.5.0

### ISSUE THREAD

**Issue by Lammerink** [droboports/crashplan#19]
Code 42 released a new version of CrashPlan 4.5.0
https://support.code42.com/Release_Notes/CrashPlan_For_Home/4.5.0

And again it breaks the install :(

Ricardo, I'd like to thank you so much for all the work you have put into supporting CrashPlan on the Drobo, they haven't made it easy!!! 

Cheers, 
Ruben

**Comment by ricardopadilha** [comment]
The bad news is that Crashplan is dead on the DroboFS. According to their 4.5.0 release information:

```
Kernel version
    CrashPlan app version 4.5.x or later: 2.6.27 or later
    CrashPlan app version 4.4.1 or earlier: 2.6.13 or later
glibc
    CrashPlan app version 4.5.x or later: 2.9 or later
    CrashPlan app version 4.4.1 or earlier: 2.4 or later
```

The DroboFS kernel is 2.6.22.18 and its glibc is 2.5.

**Comment by smenzer** [comment]
I take it there's no way to upgrade the kernel on DroboFS?

**Comment by ricardopadilha** [comment]
Well, nothing is impossible but let's just say that this would be extremely hard to do. Not to mention warranty-voiding, but I guess all DroboFS owners are beyond that at this point in time.

I'm packaging 4.5.0 for the 5N right now, and although I do not want to give false hope, I think that I might be able to make it work on the FS after all. Stay tuned.

**Comment by smenzer** [comment]
I just got a note from Crashplan saying the versions were wrong before and that these are the accurate ones:
>On December 1st, 2015, we reached out to you to inform you that our Linux System Requirements for CrashPlan have changed beginning with version 4.5. However, the new minimum requirements that we stated in this email were incorrect. The correct Linux kernel System Requirements for CrashPlan are:

>`CrashPlan app version 4.5.x or later: kernel 2.6.32 or newer and glibc 2.9+`
>`CrashPlan app version 4.4.1 or earlier: kernel 2.6.13 or newer and glibc 2.4+`

**Comment by ricardopadilha** [comment]
If I understand correctly version 4.4.1 will continue to work on the DroboFS, but the problem is that 4.4.1 is the end of line for DroboFS unless I manage work around this: https://support.code42.com/CrashPlan/4/Troubleshooting/Linux_CrashPlan_App_Version_4.5_Cannot_Back_Up

**Comment by jcollao** [comment]
We also have to make sure that our computers stay at version 4.4.1 to be compatible with the DroboFS. 

If you backup to a DroboFS and Crashplan server, your client will be updated to 4.5, which will break the backups to the DroboFS.

**Comment by ricardopadilha** [comment]
> We also have to make sure that our computers stay at version 4.4.1 to be compatible with the DroboFS.

Well, that is something that I cannot confirm. I'm currently running 4.5.0 on my 5N, and my 4.4.1 desktop is backing up just fine to it.

Not only that, I can use my 4.4.1 GUI to manage the 4.5.0 server running on the 5N.

**Comment by jcollao** [comment]
Here's the section from the link you shared which I am referring to. I read it wrong, says "may not work", not "will not work". My bad. 

Computer-to-Computer Backups
If you back up data from one device to another device (rather than to the Code42 cloud or an enterprise server), both devices must use the same version of the CrashPlan app.
If one of your devices is prevented from upgrading but your other devices will be automatically upgraded as normal, your computer-to-computer backups may not function as expected. This is expected behavior for mismatched versions of the CrashPlan app.

**Comment by ricardopadilha** [comment]
Commit 210e4b3 updates the DroboApp to 4.5.0. The TGZ for the 5N can be found here: https://github.com/droboports/crashplan/releases/tag/v4.5.0

**Comment by ricardopadilha** [comment]
I submitted a new ticket especifically to handle the DroboFS issue. See #20.
