### ISSUE TITLE
Crash plan does not start anymore

### ISSUE THREAD

**Issue by dmzettl** [droboports/crashplan#23]
Hi,

Crashplan stopped working 3 days ago and it does not start anymore. From what I can see, it is connected with Java. But I can't see anything specific from the log files. Maybe someone can point me in the right direction how to decipher the log files, so that I can resolve the issue.

Thanks,
Dietmar

**Comment by ricardopadilha** [comment]
Which version of the app are you using? Which device are you running it on (5N, FS)? Are the Java and Locale apps installed and running?

**Comment by scdemanett** [comment]
I'm pretty sure this is related to the latest update of Crashplan. I have the same issue on the 5N and uninstalling and reinstalling from the Dashboard gets it running but once it tries to update to 4.7.0 it breaks and won't start.

**Comment by dmzettl** [comment]
Hi Ricardo,

I'm running of crashplan 4.6.0.5  on a Drobo 5N. I installed 4.6.0.5 as you
suggested in a previous post, directly from the Drobo Dashboard.

Both Java and Locale apps are installed and running.
I experienced no problems so far.

Cheers,
Dietmar



2016-05-17 16:25 GMT+02:00 Ricardo Padilha <notifications@github.com>:

> Which version of the app are you using? Which device are you running it on
> (5N, FS)? Are the Java and Locale apps installed and running?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/droboports/crashplan/issues/23#issuecomment-219734094>
>



-- 
Mag. Dietmar Zettl
Mühlbachergasse 13/6
1130 Wien
E-Mail: dmzettl@acm.org
Mobil: +43.664.847.2213

**Comment by ricardopadilha** [comment]
A new version of CrashPlan was released. I have updated the app and it is now available from Drobo Dashboard for upgrade.

**Comment by dmzettl** [comment]
Hi Ricardo,

Thank you so much - you did it again! I installed crashplan from Drobo
Dashboard and everything works perfectly, again.

Again, many thanks for helping me out!

Cheers,
Dietmar


2016-05-20 0:57 GMT+02:00 Ricardo Padilha <notifications@github.com>:

> A new version of CrashPlan was released. I have updated the app and it is
> now available from Drobo Dashboard for upgrade.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/droboports/crashplan/issues/23#issuecomment-220469555>
>



-- 
Mag. Dietmar Zettl
Mühlbachergasse 13/6
1130 Wien
E-Mail: dmzettl@acm.org
Mobil: +43.664.847.2213
