### ISSUE TITLE
Automatic update strikes again

### ISSUE THREAD

**Issue by dmzettl** [droboports/crashplan#25]
Hi there,

I'm running crashplan 4.6.0.5  on a Drobo 5N.
Both apps Java and locale are installed and running.

10 days or so crashplan stopped working on my Drobo. Reason: it again tries to install an update.
So, what I did yesterday: uninstall of Drobo crashplan 4.5.2 and re-installation. It then worked and stopped working today.

I thought the automatic update has been disabled, hasn't it?

Thanks for any help. It seems I'm the only one using crashplan, because nobody else reported this problem. I guess, I have to consider moving away from crashplan as well. This is not the kind of service I expect.

Cheers,
Dietmar

**Comment by ricardopadilha** [comment]
I was beta-testing a way to prevent the auto-update, which I managed to refine with 4.7.0. The new version has been submitted to the official DroboApp repository and should be available in a few days.

**Comment by dmzettl** [comment]
Hi Ricardo,

That's great! Thanks for that.

Cheers,
Dietmar

**Comment by bobwolff68** [comment]
I have had an Drobo FS for many years and just upgraded to the 5N in June. I setup Crashplan and all was well until June 21st when the service stopped. And I have tried many things to solve it. I'm a Linux admin - desktop, server, and embedded - sigh - and I cannot seem to make out the issue for certain. I unzipped the .jar in the app/upgrade/ folder and modified the upgrade.sh and ran it - no luck - looked at some of the logs and did find a suspicious exception in the java app which might be data related. Ouch. Any of this ringing a bell for anyone? I'm happy to be part of the solution and not just the problem. Let me know what to look at next and I'm happy to help out or even provide code/fixes to infrastructure or scripts. Great piece of hardware and crashplan rocks as well.

**Comment by ryanspletzer** [comment]
Similar issue @bobwolff68.

**Comment by bobwolff68** [comment]
@ricardopadilha - note I no longer have the FS model - I noted that I recently upgraded to a 5N and crashplan was working great on it until June 21st.

**Comment by bobwolff68** [comment]
To my amazement, yesterday I noticed the 'upgrade' symbol on DroboDashboard with regards to the crashplan droboapp. I gave it a shot and it worked again! I'm backing up! Was there a proactive change or did I just get a good moon phase? :)

**Comment by ricardopadilha** [comment]
I'm sorry, I forgot to mention it here. Yes, the new version is out, and this time with auto-updates disabled. Hopefully this will be the last time we get caught by surprise like this.

Thanks everyone for the patience.

**Comment by danwieder** [comment]
Are you saying that it should be ok now to upgrade the crashplan app through the drobo apps menu?
Dan Wieder
daniel.wieder@gmail.com

**Comment by ricardopadilha** [comment]
> Are you saying that it should be ok now to upgrade the crashplan app through the drobo apps menu?

Yes, it should be perfectly safe. I'm working with Drobo to push app updates through the official repository.
