### ISSUE TITLE
Crashplan 4.7.0.14 for Drobo 5N

### ISSUE THREAD

**Issue by effulgence** [droboports/crashplan#29]
Hi Richardo,

I recently just brought my Drobo 5N online after we moved from one house to another a few months ago. The Crashplan on my Drobo is still on the 4.5 version. I realize that the new versions of Crashplan no longer supports non-Intel devices. I am wondering if I could give Crashplan 4.7.0.14 a try to continue my backup. Would you be able to point me where I could download Crashplan 4.7.0.14 for Drobo? Thank you!

**Comment by ricardopadilha** [comment]
You can still find the latest release of Crashplan form the official DroboApp repository:

ftp://updates.drobo.com/droboapps/2.1/downloads/crashplan.tgz

You can install this manually by dropping the TGZ in the DroboApps share (login as admin) and restarting the Drobo.
