### ISSUE TITLE
New release: 3.7.0

### ISSUE THREAD

**Issue by deekayen** [droboports/crashplan#3]
Crashplan made a new release (3.7.0) which appears to break doing backups from my Mac to my Drobo 5N and from my Drobo 5N to Crashplan Central.

**Comment by ricardopadilha** [comment]
I have published a new release with the 3.7.0 client. Please keep in mind that I was not able to properly test this release, and won't be able to do so until next week (my 5N is offline). Use extra caution when upgrading this.

You can find it here: https://github.com/droboports/crashplan/releases/tag/v3.7.0b1

I'm gonna keep this ticket open until I'm able to give this version a good shake. Until then, if this gives you any trouble, please do no hesitate to ping back.

**Comment by deekayen** [comment]
I dropped your beta 1 tgz into the DroboApps folder by SMB, then rebooted my 5N twice, then it worked again without drastic measures.

**Comment by ricardopadilha** [comment]
I did some testing myself and the release seems to be fine.

**Comment by cmaenner** [comment]
I tried installing your 3.7.0 release (https://github.com/droboports/crashplan/releases/download/v3.7.0/crashplan.tgz) and every time I start my CrashPlan application, after 5 seconds it stops.  Do you have any recommendations in regards to why this might be happening?  

The steps I performed to install CrashPlan 3.7.0 are the following:
1. I mounted my DroboApps share and copied the crashplan.tgz into the share
2. SSH'd into my Drobo 5N and ran the command: "# /usr/bin/DroboApps.sh install"

**Comment by deekayen** [comment]
I restarted my Drobo 5N twice before it stabilized. I've re-installed twice (preserving the backupArchive folder) because I assumed that would ultimately be easier than finding the actual cause of the problem on previous upgrades. If you're already familiar with SSH, it's not a big deal.

If you don't figure it out, these are some pretty reliable instructions to re-install.
http://katiefloyd.me/blog/crashplan-on-drobo-5n-and-the-363-update
http://katiefloyd.me/blog/installing-crashplan-on-a-drobo-5n

**Comment by cmaenner** [comment]
Thanks for the information @deekayen, I tried both restarting twice as well as followed the steps in the katiefloyd.me blog.  I uninstalled and then reinstalled Locale 2.11.1 & Java 7 update 71 prior to reinstalling CrashPlan 3.7.0.  I keep having the same results of CrashPlan not starting.

Do you know of any resources that may help me understand what is causing the CrashPlan application to crash?
