### ISSUE TITLE
I cannot get this stopped or uninstalled from my 5N

### ISSUE THREAD

**Issue by joelschou** [droboports/crashplan#31]
I've had the crashplan app installed on my 5N for a few years, despite the unfortunate timing of C42 dropping their home user plans shortly after doing so. For the longest time, I just ignored the app since I'd never set it up, but I really want it gone now. It refuses to stop or uninstall via the Drobo Dashboard app on my iMac and I cannot manually delete any files via the Finder or SSH. I've tried any number of sudo tricks, including attempting to chown everything to my admin user. Alas, I get "permission denied" on the entirety of the `/app/upgrade` folder every single time. Any ideas?

**Comment by ricardopadilha** [comment]
Sorry for the inconvenience. This is a low-level trick I had to use to prevent Crashplan from nuking itself on a botched upgrade. You need to change the "immutable" attribute of the /app/upgrade folder, using something like this:
`chattr -i /mnt/DroboFS/Shares/DroboApps/crashplan/app/upgrade`
After that you'll be able to delete it.

**Comment by joelschou** [comment]
🎉 

Thank you so much.
