### ISSUE TITLE
New Release: Crashplan 4.2.0

### ISSUE THREAD

**Issue by Lammerink** [droboports/crashplan#4]
This was just released. Crashplan 4.2.0

http://support.code42.com/Release_Notes/CrashPlan_For_Home/4.2.0

**Comment by ricardopadilha** [comment]
Thanks for the heads up.

**Comment by deekayen** [comment]
I confirmed my 4.2.0 desktop client can't backup to to my 3.7.0 Drobo 5N anymore.

**Comment by ricardopadilha** [comment]
The new 4.2.0 version is out. Check the releases page for 5N and FS versions.
